version: '3.8'
services:
  db:
    container_name:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
    ports:
      - '5432:5432'
  pgadmin:
    container_name: beme_dbadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL:
      PGADMIN_DEFAULT_PASSWORD:
    ports:
      - '5050:80'
  frontend:
    container_name:
    image:
    restart: always
    ports:
      - '8080:80'
  api:
    container_name:
    image:
    restart: always
    ports:
      - '3021:3021'
  discord:
    container_name:
    image:
    restart: always
    ports:
      - '4021:4021'
